### ISSUE TITLE
Server 500 error when joining a team in demo enviornment

### ISSUE THREAD

**Issue by d0nutptr** [elespike/Asteria#1]
I am unable to join another team in the demo environment. I am not sure if this is a technical issue with the code or if it's an issue with this particular deployment.

**Comment by elespike** [comment]
What are the steps to recreate?
I was able to register a user/team, then jump to a new team without issue.

**Comment by elespike** [comment]
Fixed with https://github.com/elespike/Asteria/commit/75e896100ed0b67d8621717e5ae6feb49f96e4f0

Nice catch, thanks!
