### ISSUE TITLE
I'm not sure if this is supposed to say this.... :P

### ISSUE THREAD

**Issue by d0nutptr** [elespike/Asteria#2]
https://github.com/elespike/Asteria/blob/2c181854de253b56f93393d545434c4fe3930802/teams/forms.py#L96

**Comment by elespike** [comment]
Of course it is XD
That's someone trying to hack the framework.

**Comment by elespike** [comment]
Functioning to spec :D

**Comment by d0nutptr** [comment]
Hahaha fair enuf ;P Wasn't sure if it was "accidentally" left in a while back. 

I suspect it's reasonable to argue that if you saw this message that you kind of deserved it and have little reason to complain :)
